name: "hcahps_healthcare"
version: "1.0.0"
config-version: 2

profile: "default"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  hcahps_healthcare:
    staging:
      +materialized: view
      +schema: STAGING_SILVER
    marts:
      +materialized: table
      +schema: GOLD_MARTS
    reports:
      +materialized: table
      +schema: REPORTS